---
- hosts: all
  vars:
    initiator_name: 'none'
  gather_facts: no
  become: true
  tasks:
    - name: Packages
      ansible.builtin.package:
        name:
          - tmux
          - vim
          - bash
          - curl
          - util-linux
          - grep
          - gawk
          - nfs-utils
        state: present

    - name: Install iscsi-initiator-utils
      ansible.builtin.package:
        name:
          - iscsi-initiator-utils
        state: present

    - name: Get current initiator name from initiatorname.iscsi
      ansible.builtin.slurp:
        src: /etc/iscsi/initiatorname.iscsi
      register: initiator_name_content
      ignore_errors: yes

    - name: Get the initiator name if not found in initiatorname.iscsi
      ansible.builtin.command: /sbin/iscsi-iname
      register: initiator_name
      when: initiator_name_content.failed

    - name: Write the initiator name to initiatorname.iscsi
      ansible.builtin.copy:
        dest: /etc/iscsi/initiatorname.iscsi
        content: "InitiatorName={{ initiator_name.stdout }}\n"
      when: initiator_name_content.failed

    - name: Enable and start iscsid service
      ansible.builtin.systemd:
        name: iscsid
        enabled: yes
        state: started

