---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Packages
      ansible.builtin.package:
        name:
          - tmux
          - vim
          - bash
          - curl
          - util-linux
          - grep
          - gawk
          - nfs-utils
        state: present

