---
- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
    
    - name: Get current locale and language configuration
      command: localectl status
      register: locale_status
    
    - name: Parse 'LANG' from current locale and language configuration
      set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"
    
    - name: Configure locale to {{ config.locale }}
      command: localectl set-locale LANG={{ system.locale }}
      when: locale_lang != system.locale

    - name: Set timezone to {{ system.timezone }}
      community.general.timezone:
        name: "{{ system.timezone }}"
